### ISSUE TITLE
Cannot find any reads matching

### ISSUE THREAD

**Issue by jloubser** [APHA-CSU/btb-seq#90]
Hi! I'm trying to run the pipeline but I think I might be missing/misunderstanding something.
here is my command:
nextflow run APHA-CSU/btb-seq -with-docker aphacsubot/btb-seq --reads='/home/ubuntu/pamela/fastqs/' --outdir='/home/ubuntu/pamela/outputs/'

The error: 
Cannot find any reads matching: /home/ubuntu/pamela/fastqs/

I'm not sure how to implement the instructions; should I add *_R1.*fastq.gz as part of the reads directory?
The structure of the filenames are:
PN18073-3_S12_L001_R1.fastq.gz
PN18073-3_S12_L001_R2.fastq.gz
I renamed these to a more simple structure and got the same error.

Any help would be appreciated :-)
I pulled the docker image and did not do a local installation.

**Comment by ellisrichardj** [comment]
@jloubser Looks like you need to add the pattern matching for the files as part of the `reads` parameter.

In your case you would need `--reads='/home/ubuntu/pamela/fastqs/*_{S_*R1,S*_R2}.fastq.gz`
I hope that helps

**Comment by jloubser** [comment]
@ellisrichardj brilliant! it works, thank you!
