### ISSUE TITLE
RAM requirement

### ISSUE THREAD

**Issue by jloubser** [APHA-CSU/btb-seq#91]
Hi there,

Quick sanity check perhaps...
I'm using this pipeline very successfully on a multipass Ubuntu instance . I can afford 4GB RAM since my system has 16GB.
I'm replicating the same instance for someone else, but the only difference is their instance can only be 2GB (since their machine only has 8GB).

We get the same error every time. At the deduplicate stage the pipeline gets killed.
I'm 99% sure that it's not a pipeline issue as the two instances are identical, except for the RAM. I'm using the exact same sequences too.

If it's RAM, is there a workaround for this perhaps?

*apologies if this is more a system requirement question than anything else.

**Comment by ellisrichardj** [comment]
I doubt this pipeline would run with such low memory available.  Many parts of the process require significant amounts of memory.  In routine use we are using 8-core 32GB RAM, and this allows for efficient parallelization.   The amount of memory required for deduplication is correlated to the size of the input file, so perhaps subsampling the input might allow that part to run, but then there would likely be insufficient data to generate a useable output.
